### ISSUE TITLE
Set up the software stack on the Jetson

### ISSUE THREAD

**Issue by wheitman** [Voltron-UTD/meta#2]
- [x] Set boot disk to main USB SSD (this is complicated)
- [ ] Set up backup disk (still complicated)
- [x] Flash with latest version of [L4T](https://developer.nvidia.com/embedded/linux-tegra) using [JetPack](https://developer.nvidia.com/EMBEDDED/Jetpack)
- [x] Install Docker
- [ ] ADE
- [x] Install NVIDIA SDK (CUDA, cuDNN, OpenCV, etc)
- [ ] Import existing .aderc

**Comment by wheitman** [comment]
The Jetson is flashed! I'll try to save it as a .img file so that we can easily reset things in the future. I still need to install our software containers. I won't be installing LGSVL, since having a simulator installed on the vehicle is probably not necessary.

It's possible that we'll have to forgo ADE and instead using something like Docker Compose to run all our containers properly.

**Comment by wheitman** [comment]
Gave ADE another shot, but it looks like we'll have to go with Compose. Looks like a more full-featured tool anyway. I'm piecing together code snippets from various sites to form the docker-compose.yml file, and I've arrived at something like this:

```
version: "3.9" 
services:
  autoware:
    image: registry.gitlab.com/autowarefoundation/autoware.auto/autowareauto/arm64/ade-foxy:master
  ros:
    image: ros:foxy
volumes:
  lunavolume01: {}
```

This version only loads ros and autoware (obviously), but you can enter a container with `docker exec autoware sh` (for autoware, for example). Ideally we'll create a nice, custom "base" image (like vde) that will depend on the others, and we'll enter the base container.

Anyway, Docker Compose looks very exciting. We'll only need to share a single file, and all developers and the vehicle will share identical environments.

If anyone happens to see this, thoughts are appreciated!
